"""Visualize a Liberty timing model (.lib) generated by OpenSTA.

Parses the timing model and produces:
  1. Pin map diagram (inputs / outputs grouped by AXI channel)
  2. Setup / Hold constraint bar chart for input pins
  3. NLDM delay curves (cell_rise / cell_fall vs load capacitance)
  4. Propagation delay distribution across output pins
  5. Transition time curves

Usage:
    python3 scripts/viz-timing-model.py <timing_model_file> [-o output_dir]
"""

import re
import os
import sys
from argparse import ArgumentParser
from collections import defaultdict

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np


# ---------------------------------------------------------------------------
# Liberty parser (minimal, targeting OpenSTA timing_model output)
# ---------------------------------------------------------------------------

def parse_liberty(filepath):
    """Parse a Liberty timing model file and return structured data."""
    with open(filepath, "r") as f:
        text = f.read()

    lib = {
        "name": "",
        "attributes": {},
        "types": {},
        "cell": None,
    }

    # Library name
    m = re.search(r'library\s*\(\s*(\w+)\s*\)', text)
    if m:
        lib["name"] = m.group(1)

    # Simple key-value attributes at library level
    for m in re.finditer(r'^\s+([\w_]+)\s*:\s*(.+?)\s*;', text, re.MULTILINE):
        lib["attributes"][m.group(1)] = m.group(2).strip('"')

    # lu_table_template
    tmpl_m = re.search(
        r'lu_table_template\s*\(\s*(\w+)\s*\)\s*\{[^}]*index_1\s*\(\s*"([^"]+)"\s*\)',
        text,
    )
    if tmpl_m:
        lib["template_name"] = tmpl_m.group(1)
        lib["template_index"] = [float(x) for x in tmpl_m.group(2).split(",")]

    # Parse cell
    cell_m = re.search(r'cell\s*\(\s*"(\w+)"\s*\)\s*\{', text)
    if not cell_m:
        print("Error: no cell found in liberty file")
        sys.exit(1)

    cell_name = cell_m.group(1)
    cell_start = cell_m.end()

    # Area
    area_m = re.search(r'area\s*:\s*([\d.]+)', text[cell_start:])
    area = float(area_m.group(1)) if area_m else 0.0

    # Parse all pins (both standalone and inside bus groups)
    pins = []
    buses = {}

    # Find bus groups
    for bm in re.finditer(
        r'bus\s*\(\s*"([\w\[\]]+)"\s*\)\s*\{[^}]*?bus_type\s*:\s*(\w+)\s*;'
        r'\s*direction\s*:\s*(\w+)\s*;',
        text,
    ):
        bus_name = bm.group(1)
        buses[bus_name] = {"direction": bm.group(3), "pins": []}

    # Parse individual pins
    pin_pattern = re.compile(
        r'pin\s*\(\s*"([\w\[\]]+)"\s*\)\s*\{', re.MULTILINE
    )
    for pm in pin_pattern.finditer(text, cell_start):
        pin_name = pm.group(1)
        # Extract the block for this pin (find matching brace)
        pin_start = pm.end()
        depth = 1
        i = pin_start
        while i < len(text) and depth > 0:
            if text[i] == '{':
                depth += 1
            elif text[i] == '}':
                depth -= 1
            i += 1
        pin_block = text[pin_start:i - 1]

        pin_info = _parse_pin_block(pin_name, pin_block)
        pins.append(pin_info)

        # Associate with bus
        base = re.sub(r'\[\d+\]$', '', pin_name)
        for bname in buses:
            if pin_name.startswith(bname.replace("[]", "")) or base == bname:
                buses[bname]["pins"].append(pin_info)
                break

    lib["cell"] = {
        "name": cell_name,
        "area": area,
        "pins": pins,
        "buses": buses,
    }
    return lib


def _parse_pin_block(pin_name, block):
    """Parse a single pin block and extract timing arcs."""
    info = {"name": pin_name, "direction": "unknown", "capacitance": 0.0,
            "clock": False, "timing_arcs": []}

    dm = re.search(r'direction\s*:\s*(\w+)', block)
    if dm:
        info["direction"] = dm.group(1)

    cm = re.search(r'capacitance\s*:\s*([\d.]+)', block)
    if cm:
        info["capacitance"] = float(cm.group(1))

    if re.search(r'clock\s*:\s*true', block):
        info["clock"] = True

    # Parse timing arcs
    for tm in re.finditer(r'timing\s*\(\s*\)\s*\{', block):
        arc_start = tm.end()
        depth = 1
        j = arc_start
        while j < len(block) and depth > 0:
            if block[j] == '{':
                depth += 1
            elif block[j] == '}':
                depth -= 1
            j += 1
        arc_block = block[arc_start:j - 1]
        arc = _parse_timing_arc(arc_block)
        info["timing_arcs"].append(arc)

    return info


def _parse_timing_arc(block):
    """Parse a timing() block."""
    arc = {}

    rp = re.search(r'related_pin\s*:\s*"(\w+)"', block)
    if rp:
        arc["related_pin"] = rp.group(1)

    ts = re.search(r'timing_sense\s*:\s*(\w+)', block)
    if ts:
        arc["timing_sense"] = ts.group(1)

    tt = re.search(r'timing_type\s*:\s*(\w+)', block)
    if tt:
        arc["timing_type"] = tt.group(1)

    # Scalar constraints (setup/hold)
    for kind in ("rise_constraint", "fall_constraint"):
        m = re.search(kind + r'\s*\(\s*scalar\s*\)\s*\{\s*values\s*\(\s*"([^"]+)"\s*\)', block)
        if m:
            arc[kind] = float(m.group(1))

    # NLDM tables
    for kind in ("cell_rise", "cell_fall", "rise_transition", "fall_transition"):
        m = re.search(
            kind + r'\s*\(\s*\w+\s*\)\s*\{'
            r'\s*index_1\s*\(\s*"([^"]+)"\s*\)\s*;'
            r'\s*values\s*\(\s*"([^"]+)"\s*\)',
            block,
        )
        if m:
            arc[kind + "_index"] = [float(x) for x in m.group(1).split(",")]
            arc[kind + "_values"] = [float(x) for x in m.group(2).split(",")]

    return arc


# ---------------------------------------------------------------------------
# Classify pins into AXI channels / groups
# ---------------------------------------------------------------------------

AXI_CHANNEL_ORDER = ["AR", "R", "AW", "W", "B", "other", "ctrl"]

def classify_pin(name):
    """Return (channel, signal) for AXI-like pin naming."""
    name_lower = name.lower().replace("io_master_", "")
    if name_lower.startswith("ar"):
        return "AR"
    if name_lower.startswith("r"):
        return "R"
    if name_lower.startswith("aw"):
        return "AW"
    if name_lower.startswith("w"):
        return "W"
    if name_lower.startswith("b"):
        return "B"
    if name_lower in ("clock", "reset", "io_interrupt"):
        return "ctrl"
    return "other"


def group_pins(pins):
    """Group pins by AXI channel, collapsing bus bits into bus-level entries."""
    buses = defaultdict(lambda: {"direction": None, "bits": [], "timing_arcs": []})
    standalone = []

    for p in pins:
        bm = re.match(r'(.*)\[(\d+)\]$', p["name"])
        if bm:
            bus_name = bm.group(1)
            buses[bus_name]["bits"].append(p)
            if p["direction"] != "unknown":
                buses[bus_name]["direction"] = p["direction"]
            if p["timing_arcs"]:
                buses[bus_name]["timing_arcs"].extend(p["timing_arcs"])
        else:
            standalone.append(p)

    groups = defaultdict(list)
    for p in standalone:
        ch = classify_pin(p["name"])
        groups[ch].append({
            "name": p["name"],
            "width": 1,
            "direction": p["direction"],
            "capacitance": p["capacitance"],
            "timing_arcs": p["timing_arcs"],
            "clock": p.get("clock", False),
        })

    for bus_name, binfo in buses.items():
        ch = classify_pin(bus_name)
        width = len(binfo["bits"])
        cap = max((b["capacitance"] for b in binfo["bits"]), default=0.0)
        groups[ch].append({
            "name": bus_name,
            "width": width,
            "direction": binfo["direction"] or "unknown",
            "capacitance": cap,
            "timing_arcs": binfo["timing_arcs"],
            "clock": False,
        })

    return groups


# ---------------------------------------------------------------------------
# Plotting helpers
# ---------------------------------------------------------------------------

def _short_name(name):
    """Abbreviate long pin names for labels."""
    return name.replace("io_master_", "")


def _setup_style():
    plt.rcParams.update({
        "figure.facecolor": "white",
        "axes.facecolor": "#fafafa",
        "axes.grid": True,
        "grid.alpha": 0.3,
        "font.size": 10,
    })


# ---------------------------------------------------------------------------
# Fig 1: Pin Map
# ---------------------------------------------------------------------------

def plot_pin_map(cell, groups, out_dir):
    """Draw a chip-like pin map with inputs on left, outputs on right."""
    inputs = []
    outputs = []

    for ch in AXI_CHANNEL_ORDER:
        for g in groups.get(ch, []):
            label = _short_name(g["name"])
            if g["width"] > 1:
                label += f" [{g['width']}]"
            entry = (ch, label, g)
            if g["direction"] == "input":
                inputs.append(entry)
            elif g["direction"] == "output":
                outputs.append(entry)

    n_rows = max(len(inputs), len(outputs), 1)
    fig_h = max(4, n_rows * 0.35 + 1.5)
    fig, ax = plt.subplots(figsize=(12, fig_h))

    ch_colors = {
        "AR": "#4e79a7", "R": "#59a14f", "AW": "#e15759",
        "W": "#f28e2b", "B": "#b07aa1", "other": "#999999", "ctrl": "#76b7b2",
    }

    # Draw cell rectangle
    box_left, box_right = 0.30, 0.70
    box_top, box_bot = 0.92, max(0.08, 0.92 - n_rows * 0.04)
    rect = mpatches.FancyBboxPatch(
        (box_left, box_bot), box_right - box_left, box_top - box_bot,
        boxstyle="round,pad=0.01", facecolor="#e8e8e8", edgecolor="black", linewidth=1.5,
    )
    ax.add_patch(rect)
    ax.text(
        (box_left + box_right) / 2, (box_top + box_bot) / 2,
        f"{cell['name']}\nArea: {cell['area']:,.0f}",
        ha="center", va="center", fontsize=13, fontweight="bold",
    )

    def draw_pins(entries, x_text, x_line, ha, side):
        y_step = (box_top - box_bot) / (len(entries) + 1) if entries else 1
        for i, (ch, label, g) in enumerate(entries):
            y = box_top - (i + 1) * y_step
            color = ch_colors.get(ch, "#999")
            ax.annotate(
                label, xy=(x_line, y), xytext=(x_text, y),
                ha=ha, va="center", fontsize=7.5,
                arrowprops=dict(arrowstyle="-", color=color, lw=1.2),
                color=color, fontweight="bold",
            )

    draw_pins(inputs, 0.05, box_left, "right", "left")
    draw_pins(outputs, 0.95, box_right, "left", "right")

    # Legend
    handles = [mpatches.Patch(color=ch_colors[ch], label=ch) for ch in AXI_CHANNEL_ORDER if ch in ch_colors]
    ax.legend(handles=handles, loc="lower center", ncol=len(handles), fontsize=8,
              frameon=False, bbox_to_anchor=(0.5, -0.02))

    ax.set_xlim(0, 1)
    ax.set_ylim(box_bot - 0.06, box_top + 0.04)
    ax.axis("off")
    ax.set_title(f"Pin Map — {cell['name']}", fontsize=14, pad=10)
    fig.tight_layout()
    path = os.path.join(out_dir, "timing_pin_map.svg")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# Fig 2: Setup / Hold constraints
# ---------------------------------------------------------------------------

def plot_setup_hold(pins, out_dir, cell_name):
    """Bar chart of setup & hold timing constraints for input pins."""
    entries = []
    for p in pins:
        if p["direction"] != "input":
            continue
        for arc in p["timing_arcs"]:
            tt = arc.get("timing_type", "")
            if tt not in ("setup_rising", "hold_rising"):
                continue
            rise = arc.get("rise_constraint", 0.0)
            fall = arc.get("fall_constraint", 0.0)
            # Use the worst-case (max abs) of rise/fall
            val = rise if abs(rise) >= abs(fall) else fall
            entries.append((_short_name(p["name"]), tt, val))

    if not entries:
        return

    # Separate setup and hold
    setup = {n: v for n, t, v in entries if t == "setup_rising"}
    hold = {n: v for n, t, v in entries if t == "hold_rising"}
    names = sorted(set(setup.keys()) | set(hold.keys()))

    if not names:
        return

    x = np.arange(len(names))
    w = 0.35

    fig, ax = plt.subplots(figsize=(max(6, len(names) * 0.8), 5))
    setup_vals = [setup.get(n, 0) for n in names]
    hold_vals = [hold.get(n, 0) for n in names]

    ax.bar(x - w / 2, setup_vals, w, label="Setup", color="#4e79a7", edgecolor="white")
    ax.bar(x + w / 2, hold_vals, w, label="Hold", color="#e15759", edgecolor="white")

    ax.set_xticks(x)
    ax.set_xticklabels(names, rotation=45, ha="right", fontsize=9)
    ax.set_ylabel("Constraint (ns)")
    ax.set_title(f"Setup / Hold Constraints — {cell_name}", fontsize=13)
    ax.legend()
    ax.axhline(0, color="black", linewidth=0.5)
    fig.tight_layout()
    path = os.path.join(out_dir, "timing_setup_hold.svg")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# Fig 3: NLDM delay curves
# ---------------------------------------------------------------------------

def plot_nldm_curves(pins, out_dir, cell_name, max_pins=20):
    """Plot cell_rise / cell_fall delay vs output load capacitance."""
    rise_curves = []
    fall_curves = []

    for p in pins:
        if p["direction"] != "output":
            continue
        for arc in p["timing_arcs"]:
            idx_r = arc.get("cell_rise_index")
            val_r = arc.get("cell_rise_values")
            idx_f = arc.get("cell_fall_index")
            val_f = arc.get("cell_fall_values")
            label = _short_name(p["name"])
            rp = arc.get("related_pin", "clk")
            tt = arc.get("timing_type", "")
            tag = f"{label} ({tt[:4]})" if tt else label
            if idx_r and val_r:
                rise_curves.append((tag, rp, idx_r, val_r))
            if idx_f and val_f:
                fall_curves.append((tag, rp, idx_f, val_f))

    if not rise_curves and not fall_curves:
        return

    # Deduplicate by (index_tuple, values_tuple) — many pins share identical curves
    def dedup(curves):
        seen = {}
        for tag, rp, idx, val in curves:
            key = (tuple(idx), tuple(val))
            if key not in seen:
                seen[key] = []
            seen[key].append(tag)
        result = []
        for (idx, val), tags in seen.items():
            if len(tags) > 3:
                label = f"{tags[0]} ... ({len(tags)} pins)"
            else:
                label = ", ".join(tags)
            result.append((label, list(idx), list(val)))
        return result

    rise_dedup = dedup(rise_curves)
    fall_dedup = dedup(fall_curves)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=False)

    cmap = plt.cm.tab10
    for ax, curves, title in [
        (axes[0], rise_dedup, "Cell Rise Delay"),
        (axes[1], fall_dedup, "Cell Fall Delay"),
    ]:
        for i, (label, idx, val) in enumerate(curves[:max_pins]):
            color = cmap(i % 10)
            ax.plot(idx, val, "o-", markersize=3, label=label, color=color, linewidth=1.5)
        ax.set_xlabel("Output Load Capacitance (fF)")
        ax.set_ylabel("Delay (ns)")
        ax.set_title(title)
        if len(curves) <= 10:
            ax.legend(fontsize=7, loc="upper left")

    fig.suptitle(f"NLDM Delay Curves — {cell_name}", fontsize=14)
    fig.tight_layout()
    path = os.path.join(out_dir, "timing_nldm_delay.svg")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# Fig 4: Propagation delay distribution
# ---------------------------------------------------------------------------

def plot_delay_distribution(pins, out_dir, cell_name):
    """Histogram of propagation delays (cell_rise at min load) for outputs."""
    delays_rise = []
    delays_fall = []
    labels = []

    for p in pins:
        if p["direction"] != "output":
            continue
        for arc in p["timing_arcs"]:
            val_r = arc.get("cell_rise_values")
            val_f = arc.get("cell_fall_values")
            if val_r:
                delays_rise.append(val_r[0])  # delay at minimum load
                labels.append(_short_name(p["name"]))
            if val_f:
                delays_fall.append(val_f[0])

    if not delays_rise:
        return

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # Histogram
    ax = axes[0]
    bins = np.linspace(0, max(max(delays_rise), max(delays_fall)) * 1.1, 30)
    ax.hist(delays_rise, bins=bins, alpha=0.7, label="Rise delay", color="#4e79a7", edgecolor="white")
    ax.hist(delays_fall, bins=bins, alpha=0.7, label="Fall delay", color="#e15759", edgecolor="white")
    ax.set_xlabel("Delay at min load (ns)")
    ax.set_ylabel("Number of pins")
    ax.set_title("Delay Distribution")
    ax.legend()

    # Sorted bar chart for top delays
    ax2 = axes[1]
    paired = sorted(zip(delays_rise, labels), reverse=True)
    top_n = min(25, len(paired))
    top_delays = [d for d, _ in paired[:top_n]]
    top_labels = [l for _, l in paired[:top_n]]
    y_pos = np.arange(top_n)
    ax2.barh(y_pos, top_delays, color="#4e79a7", edgecolor="white", height=0.7)
    ax2.set_yticks(y_pos)
    ax2.set_yticklabels(top_labels, fontsize=7)
    ax2.invert_yaxis()
    ax2.set_xlabel("Rise Delay at min load (ns)")
    ax2.set_title(f"Top {top_n} Slowest Output Pins")

    fig.suptitle(f"Propagation Delay Overview — {cell_name}", fontsize=14)
    fig.tight_layout()
    path = os.path.join(out_dir, "timing_delay_dist.svg")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# Fig 5: Transition time curves
# ---------------------------------------------------------------------------

def plot_transition_curves(pins, out_dir, cell_name, max_pins=20):
    """Plot rise/fall transition time vs load capacitance."""
    rise_curves = []
    fall_curves = []

    for p in pins:
        if p["direction"] != "output":
            continue
        for arc in p["timing_arcs"]:
            idx_r = arc.get("rise_transition_index")
            val_r = arc.get("rise_transition_values")
            idx_f = arc.get("fall_transition_index")
            val_f = arc.get("fall_transition_values")
            label = _short_name(p["name"])
            if idx_r and val_r:
                rise_curves.append((label, idx_r, val_r))
            if idx_f and val_f:
                fall_curves.append((label, idx_f, val_f))

    if not rise_curves and not fall_curves:
        return

    def dedup(curves):
        seen = {}
        for tag, idx, val in curves:
            key = (tuple(idx), tuple(val))
            if key not in seen:
                seen[key] = []
            seen[key].append(tag)
        result = []
        for (idx, val), tags in seen.items():
            if len(tags) > 3:
                label = f"{tags[0]} ... ({len(tags)} pins)"
            else:
                label = ", ".join(tags)
            result.append((label, list(idx), list(val)))
        return result

    rise_dedup = dedup(rise_curves)
    fall_dedup = dedup(fall_curves)

    fig, axes = plt.subplots(1, 2, figsize=(14, 6), sharey=False)

    cmap = plt.cm.tab10
    for ax, curves, title in [
        (axes[0], rise_dedup, "Rise Transition Time"),
        (axes[1], fall_dedup, "Fall Transition Time"),
    ]:
        for i, (label, idx, val) in enumerate(curves[:max_pins]):
            color = cmap(i % 10)
            ax.plot(idx, val, "o-", markersize=3, label=label, color=color, linewidth=1.5)
        ax.set_xlabel("Output Load Capacitance (fF)")
        ax.set_ylabel("Transition Time (ns)")
        ax.set_title(title)
        if len(curves) <= 10:
            ax.legend(fontsize=7, loc="upper left")

    fig.suptitle(f"Transition Time Curves — {cell_name}", fontsize=14)
    fig.tight_layout()
    path = os.path.join(out_dir, "timing_transition.svg")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# Fig 6: Timing arc summary (input-to-output connectivity)
# ---------------------------------------------------------------------------

def plot_timing_arc_summary(pins, out_dir, cell_name):
    """Visualize timing arc types and combinational paths."""
    arc_types = defaultdict(int)
    combo_arcs = []  # (input, output, sense)

    for p in pins:
        for arc in p["timing_arcs"]:
            tt = arc.get("timing_type", "unknown")
            arc_types[tt] += 1
            if tt == "combinational":
                rp = arc.get("related_pin", "?")
                combo_arcs.append((rp, p["name"], arc.get("timing_sense", "")))

    if not arc_types:
        return

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))

    # Pie chart of arc types
    ax = axes[0]
    labels = list(arc_types.keys())
    sizes = list(arc_types.values())
    colors_pie = plt.cm.Set3(np.linspace(0, 1, len(labels)))
    wedges, texts, autotexts = ax.pie(
        sizes, labels=labels, autopct="%1.0f%%", colors=colors_pie,
        textprops={"fontsize": 8},
    )
    ax.set_title("Timing Arc Types")

    # Combinational paths table
    ax2 = axes[1]
    ax2.axis("off")
    if combo_arcs:
        col_labels = ["Input", "Output", "Sense"]
        table_data = [[_short_name(i), _short_name(o), s] for i, o, s in combo_arcs[:20]]
        table = ax2.table(
            cellText=table_data, colLabels=col_labels,
            loc="center", cellLoc="center",
        )
        table.auto_set_font_size(False)
        table.set_fontsize(8)
        table.scale(1, 1.3)
        ax2.set_title("Combinational Paths", fontsize=11)
    else:
        ax2.text(0.5, 0.5, "No combinational paths\n(all paths are registered)",
                 ha="center", va="center", fontsize=12, color="#666")
        ax2.set_title("Combinational Paths", fontsize=11)

    fig.suptitle(f"Timing Arc Summary — {cell_name}", fontsize=14)
    fig.tight_layout()
    path = os.path.join(out_dir, "timing_arc_summary.svg")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# Fig 7: Capacitance overview
# ---------------------------------------------------------------------------

def plot_capacitance(pins, out_dir, cell_name):
    """Bar chart of pin capacitance values."""
    entries = []
    for p in pins:
        if p["capacitance"] > 0:
            entries.append((_short_name(p["name"]), p["direction"], p["capacitance"]))

    if not entries:
        return

    entries.sort(key=lambda x: x[2], reverse=True)
    top_n = min(30, len(entries))
    entries = entries[:top_n]

    fig, ax = plt.subplots(figsize=(max(6, top_n * 0.5), 5))
    names = [e[0] for e in entries]
    caps = [e[2] for e in entries]
    colors = ["#4e79a7" if e[1] == "input" else "#e15759" for e in entries]

    y = np.arange(len(names))
    ax.barh(y, caps, color=colors, edgecolor="white", height=0.7)
    ax.set_yticks(y)
    ax.set_yticklabels(names, fontsize=8)
    ax.invert_yaxis()
    ax.set_xlabel("Capacitance (fF)")
    ax.set_title(f"Pin Capacitance (top {top_n}) — {cell_name}", fontsize=13)

    handles = [
        mpatches.Patch(color="#4e79a7", label="Input"),
        mpatches.Patch(color="#e15759", label="Output"),
    ]
    ax.legend(handles=handles, fontsize=9)
    fig.tight_layout()
    path = os.path.join(out_dir, "timing_capacitance.svg")
    fig.savefig(path, bbox_inches="tight")
    plt.close(fig)
    print(f"  -> {path}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = ArgumentParser(description="Visualize Liberty timing model")
    parser.add_argument("liberty_file", help="Path to the .timing_model (Liberty) file")
    parser.add_argument(
        "-o", "--output-dir",
        help="Output directory for SVG files (default: same as input file)",
    )
    parser.add_argument(
        "-f", "--format", default="svg", choices=["svg", "pdf", "png"],
        help="Output image format (default: svg)",
    )
    args = parser.parse_args()

    out_dir = args.output_dir or os.path.dirname(os.path.abspath(args.liberty_file))
    os.makedirs(out_dir, exist_ok=True)

    print(f"Parsing {args.liberty_file} ...")
    lib = parse_liberty(args.liberty_file)
    cell = lib["cell"]
    pins = cell["pins"]
    groups = group_pins(pins)

    print(f"Library: {lib['name']},  Cell: {cell['name']},  "
          f"Area: {cell['area']:,.0f},  Pins: {len(pins)}")
    print(f"Output directory: {out_dir}")

    _setup_style()

    print("Generating plots:")
    plot_pin_map(cell, groups, out_dir)
    plot_setup_hold(pins, out_dir, cell["name"])
    plot_nldm_curves(pins, out_dir, cell["name"])
    plot_delay_distribution(pins, out_dir, cell["name"])
    plot_transition_curves(pins, out_dir, cell["name"])
    plot_timing_arc_summary(pins, out_dir, cell["name"])
    plot_capacitance(pins, out_dir, cell["name"])
    print("Done.")


if __name__ == "__main__":
    main()
